apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: example
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: example
    app.kubernetes.io/part-of: example
  name: example
  namespace: tomas-foo
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: example
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: example
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
